
name: first workflow
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step is printing greeting
        run: echo Hello, world!
      - name: Last Step is printing goodbye
        run: |
           echo Good Bye
           echo Good Bye2
           echo Good Bye3
           
